### ISSUE TITLE
Can't send messages to the echo server with nc.

### ISSUE THREAD

**Issue by relsqui** [PSU-CS-300-Fall2015/taunet-utils#2] opened 2015-12-01 08:18 UTC
On my local machine (with my own TauNet implementation), I can successfully encrypt a test message in TauNet format and nc it to myself on the appropriate port, i.e. `cat test_message | ./ciphersaber2.py --key password | nc localhost 6283`. My listener receives the message correctly and the connection closes immediately. When I do the same thing to the echo server on barton.cs.pdx.edu, the connection hangs, and I don't receive a response. Nothing in my server code overtly closes the connection after message receipt, so I'm not sure what the difference is. (I haven't picked through yours yet to see if I can find it; if you'd like to, mine is here: https://github.com/PSU-CS-300-Fall2015/taurus/blob/master/taurusd.py)

[test_message.txt](https://github.com/PSU-CS-300-Fall2015/taunet-utils/files/48248/test_message.txt) is the cleartext TauNet message I'm using. (GitHub made me tack a .txt on there before it would let me upload it, cute.)

**Comment by BartMassey** [comment] 2015-12-01 16:47
I have replicated this, and am treating it as a bug in `taunet-echo` until I can confirm otherwise. Thanks much for the report! I'll work on it today.

**Comment by BartMassey** [comment] 2015-12-04 01:08
I'm closing this. After much debugging, it seems to be a bug in select() usage in netcat. It looks like they're not selecting properly in this case. I've managed to get correct behavior out of a C netcat I wrote myself.

The netcat code is _terribad_. Somebody should do a full rewrite.

**Closed as completed by BartMassey** 2015-12-04 01:08 UTC
Labels: invalid, wontfix
